### ISSUE TITLE
Doesn't show all processes

### ISSUE THREAD

**Issue by minton** [bytejoyhq/dm-wrapper#1]
When I run this on a server via remote desktop, with multiple users running multiple instances of the same application via Citrix, the processes do not show up.

I did try running this as admin and it made no difference.

**Comment by siegol** [comment]
We were attempting to limit the process list to only include those with a Main window handle visible. This of course won't work for an application server or Citrix. I've changed the latest build to just return the raw process list ordered by `Name` and then by `PID`. This should fix your issue.

Try release [v0.3](https://github.com/bytejoyhq/dm-wrapper/releases/tag/v0.3-beta).
